# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TechTestAF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TechTestAF

  target 'TechTestAFTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TechTestAFUITests' do
    # Pods for testing
  end

end
